spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # TODO 数据库连接地址、用户名和密码
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: zsh654321
  # TODO Redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
# 开启 MyBatis-Plus 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 项目变量
project:
  # TODO 密码加密的盐值
  salt: nx3a-dh0x-sdh7